version: '3'
services:
  python3:
    build: .
    container_name: flask_apache
    hostname: flask_apache
    tty: true
    volumes:
      - ./app:/app
      - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 18000:80